/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zzj_underlying_DataConver */

#ifndef _Included_com_zzj_underlying_DataConver
#define _Included_com_zzj_underlying_DataConver
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zzj_underlying_DataConver
 * Method:    getTestString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_zzj_underlying_DataConver_getTestString
        (JNIEnv *env, jclass);

JNIEXPORT jbyteArray JNICALL Java_com_zzj_underlying_DataConver_argbToNv21
        (JNIEnv *env, jclass, jintArray arr, jint width, jint height);

JNIEXPORT jbyteArray JNICALL Java_com_zzj_underlying_DataConver_nv21Rotate90
        (JNIEnv *env, jclass, jbyteArray arr, jint width, jint height);

JNIEXPORT jbyteArray JNICALL Java_com_zzj_underlying_DataConver_rotateYUV420Degree90
        (JNIEnv *env, jclass, jbyteArray arr, jint imageWidth, jint imageHeight);

#ifdef __cplusplus
}
#endif
#endif
unsigned char *rotateYUV420Degree90(unsigned char *data, int imageWidth, int imageHeight);
unsigned char *rotateYUV420Degree180(unsigned char *data, int imageWidth, int imageHeight);


